name:                knowledgehook-core
version:             0.1.0.0
github:              "subjective-technologies/knowledgehook-core"
license:             BSD3
author:              "Subjective Technologies"
maintainer:          "dev@subjectivetechnologies.com"
copyright:           "2025 Subjective Technologies"

extra-source-files:
- README.md

synopsis:            Mathematically principled Knowledge Hook kernel
category:            AI

description: |
  A total, pure, and testable implementation of the Algebra of Knowledge Hooks,
  modeling knowledge automation as algebraic objects with denotational semantics.

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6
- text >= 1.2
- vector >= 0.12
- mtl >= 2.2
- transformers >= 0.5
- aeson >= 2.0
- free >= 5.1
- QuickCheck >= 2.14
- hedgehog >= 1.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- DataKinds
- DerivingVia
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- OverloadedStrings
- RankNTypes
- StandaloneDeriving
- TypeFamilies
- QuantifiedConstraints

library:
  source-dirs: src

executables:
  knowledgehook-demo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - knowledgehook-core

tests:
  knowledgehook-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - knowledgehook-core
    - hspec >= 2.7
